### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by n0land0** [n0land0/fact-distract#10]
## Tasks
- [x] install depencies - carousel, slider, gsap
- [x] clean header (see design inspo)
- [x] recent facts geometric container
- [x] hamburger menu for user mgmt
- [x] saved facts carousel
