### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by n0land0** [n0land0/fact-distract#12]
## Tasks
- [x] animate logo
- [x] animate loading message
- [x] animate new facts when loaded
- [x] animate facts when added to recent history queue
- [ ] hover article to save recent fact
