### ISSUE TITLE
UI for landing page

### ISSUE THREAD

**Issue by n0land0** [n0land0/fact-distract#2]
### Tasks
- [x] Create landing page ui
- [x] Fetch on page load 
- [x] Fetch on button click
- [x] Item component
- [x] Store to recents container
- [x] Recent Item component

### User Story
As a user, I want to learn a new fact, so that I can have a conversation-starter.

### Acceptance Criteria
Scenario: User has landed on the site and is trying to use new-fact functionality
- Given: User is on the generate-fact page
- When: User first lands on the page or clicks the generate button thereafter
- Then: User should see a newly generated fact and recently-generated facts
