### ISSUE TITLE
App context

### ISSUE THREAD

**Issue by n0land0** [n0land0/fact-distract#3]
### Tasks
- [x] Set up any context to be passed to child components
- [x] Build basic Nav component
- [x] Add Routes with basic components

### User Story
As a user, I want to get and save new facts, so that I can have conversation material for awkward family dinners.

### Acceptance Criteria
Scenario: User lands on the site and is trying to see how to navigate
- Given: User first visits the site
- When: User lands on page
- Then: User can easily see options for generating, saving, UI mode, language
