### ISSUE TITLE
UI for favorites page

### ISSUE THREAD

**Issue by n0land0** [n0land0/fact-distract#4]
### Tasks
- [x] Create UI for saved facts
- [x] Conditional render for fact or prompt
- [x] Container for fact items
- [x] Item component
- [x] Prompt to add facts

### User Story
As a user, I want to save facts, so that I can revisit them later to share.

### Acceptance Criteria
Scenario: User has wants to view their collection of saved facts
- Given: User navigates to saved facts page
- When: User lands on saved facts page
- Then: User should see any saved facts, or if none, a prompt to add some
